version: '3'
services:
  db:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./node_modules:/portafolio/node_modules
  web:
    build: .
    command: bundle exec rails s puma -p 3000 -b '0.0.0.0'
    volumes:
      - .:/Dojo
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
volumes:
  postgres:
    driver: local
