version: '3'
services:
  db:
    image: postgres
    volumes:
      - dg-postgres:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec rails s puma -p 3000 -b '0.0.0.0'
    volumes:
      - .:/Dojo
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  dg-postgres:
    driver: local
